server:
  port: 9999

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        namespace: flyingjack-${spring.profiles.active} # 根据激活环境使用不同的命名空间
        server-addr: ${NACOS_HOST:192.168.31.242}:8848
    gateway:
      httpclient:
        follow-redirects: false  # 禁止跟随重定向
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/account/** # 匹配路由
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://thirdparty-service
          predicates:
            - Path=/thirdparty/captcha/verify # 匹配路由
          filters:
            - StripPrefix=1


