# 统一的redis和数据配置, 参考配置如下
# DATA ID: common-dev.yml
# Group: DEFAULT_GROUP
# 格式：YAML
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000 #5s
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
